gfortran setup fixed attempt

diff --git a/.github/workflows/test_macos_build.yml b/.github/workflows/test_macos_build.yml
--- a/.github/workflows/test_macos_build.yml
+++ b/.github/workflows/test_macos_build.yml
@@ -23,7 +23,10 @@ jobs:
         run: |
           brew update
           brew install gcc
-          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
+          bindir=/opt/homebrew/bin
+          sudo ln -fs ${bindir}/gfortran /usr/local/bin/gfortran
+          which gfortran || { echo "gfortran not found"; exit 1; }
+          gfortran --version
       - name: Install dependencies
         run: |
           cd ..
